name: Deploy Website to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to deploy'
        required: true
        default: 'latest'
      app_dir:
        description: 'Directory to the app folder containing the website'
        required: true
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag_name }}
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: |
        cd ${{ github.event.inputs.tag_name }}
        flutter pub get

    - name: Build the Flutter web app
      run: flutter build web --release

    - name: Deploy Website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.event.inputs.tag_name }}/build/web/
        cname: aaronginder.github.io
